#!/usr/bin/env python
import argparse
import sys
import os
import random
import string
import binascii
import hashlib


def main(keyFile, mFile, sigFile):
    ###########################################
    #Read key info from file#
    
    f = open(keyFile, 'r')

    nBits = string.rstrip(f.readline(), "\n")
    nBits = int(nBits)
    
    n = string.rstrip(f.readline(), "\n")
    n = int(n)
    
    e = string.rstrip(f.readline(), "\n")
    e = int(e)
    
    f.close()

    ###########################################
    #Read message from file#
    
    f = open(mFile, 'r')
    m = string.rstrip(f.readline(), "\n")
    f.close()

    ###########################################
    #Hash#

    hashval = hashlib.sha256(m).hexdigest()

    hashval_int = int(hashval, 16)
    print "this = " + str(hashval_int)

    ###########################################
    #Read value to compare to#
    
    f = open(sigFile, 'r')
    comp = string.rstrip(f.readline(), "\n")
    f.close()

    comp_int = int(comp)

    comp_sig = pow(comp_int, e, n)
    print "that = " + str(comp_sig)

    ###########################################
    #Compare#

    if(hashval_int == comp_sig):
        print "True"
    else:
        print "False"

    ###########################################


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--k", help="Key file", required=True)
    parser.add_argument("--m", help="Message file", required=True)
    parser.add_argument("--s", help="Signature file", required=True)
    args = parser.parse_args()

    main(args.k, args.m, args.s)
